---
- name: Set distribution-specific default variables
  ansible.builtin.import_tasks:
    file: defaults.yml
  tags:
    - always

- name: Assert required options have been set
  ansible.builtin.import_tasks:
    file: asserts.yml
  tags:
    - always

- name: Provision Apache Kafka Node
  ansible.builtin.import_tasks:
    file: present.yml
  when: kafka_state == 'present'
  tags:
    - always

- name: Deprovision Apache Kafka Node
  ansible.builtin.import_tasks:
    file: absent.yml
  when: kafka_state == 'absent'
  tags:
    - always
...
