---
collections:
  - name: "community.general"
    version: "10.0.1"
    type: "galaxy"

roles:
  - name: "geerlingguy.java"
    scm: git
    src: https://github.com/geerlingguy/ansible-role-java.git
    version: "2.5.0"
