# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

BROKER_LISTENER_NAME = 'BROKER'
CONTROLLER_LISTENER_NAME = 'CONTROLLER'

PORT_CONTROL_PLANE = 9093
PORT_CLIENTS = 9092

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"

  N = 3
  (1..N).each do |machine_id|

    name = "kafka#{machine_id}"
    ipv4 = "192.168.205.#{100+machine_id}"

    config.vm.network "forwarded_port", guest: PORT_CLIENTS, host: PORT_CLIENTS + machine_id * 10000
    config.vm.network "forwarded_port", guest: PORT_CONTROL_PLANE, host: PORT_CONTROL_PLANE + machine_id * 10000

    config.vm.define name do |machine|
      machine.vm.hostname = name
      machine.vm.network :private_network, :ip => ipv4
      machine.vm.provider :libvirt do |v|
        v.memory = 2048
        v.cpus = 2
      end

      machine.vm.provision :ansible do |ansible|

        ansible.playbook = "site.yml"

        # create a dictionary of extra variables including the
        # list of all kafka quorum members
        ansible.extra_vars = {
          kafka_java_home: "/usr/lib/jvm/java-1.17.0-openjdk-amd64",
          kafka_cluster_id: "local-cluster",
          kafka_server_node_id: machine_id,
          kafka_listeners: [
            {
              name: BROKER_LISTENER_NAME,
              host: ipv4,
              port: PORT_CLIENTS,
              type: "broker",
              sasl: {
                enabled: true,
                plain: true,
                scram_sha_256: false,
                scram_sha_512: false,
              },
              advertise: true,
            },
            {
              name: CONTROLLER_LISTENER_NAME,
              host: ipv4,
              port: PORT_CONTROL_PLANE,
              type: "controller",
              sasl: {
                enabled: true,
                plain: true,
                scram_sha_256: false,
                scram_sha_512: false,
              },
            },
          ],
          kafka_listener_name_inter_broker: BROKER_LISTENER_NAME,
          kafka_listener_name_controller_quorum: CONTROLLER_LISTENER_NAME,
          kafka_controller_quorum_voters: (1..N).map do |node_id|
            {
              "node_id" => node_id,
              "host" => "192.168.205.#{100+node_id}",
              "port" => PORT_CONTROL_PLANE,
            }
          end,
        }

      end
    end
  end

end
