---
- name: Install RPM package.
  ansible.builtin.dnf:
    name: "{{ redpanda_console_package_download_result.dest }}"
    state: present
    allow_downgrade: true
    disable_gpg_check: true
  when: redpanda_console_package_format_file_suffix == 'rpm'

- name: Install DEB package.
  ansible.builtin.apt:
    deb: "{{ redpanda_console_package_download_result.dest }}"
    state: present
    allow_downgrade: true
  when: redpanda_console_package_format_file_suffix == 'deb'

- name: install | Create configuration file redpanda-console-config.yaml in {{ redpanda_console_config_dir_path }}
  ansible.builtin.template:
    src: templates/etc/redpanda/redpanda-console-config.yaml.j2
    dest: "{{ redpanda_console_config_dir_path }}/redpanda-console-config.yaml"
    owner: root
    group: root
    mode: u=rw-x,g=rw-x,o=r-x
  register: redpanda_console_config_file
  notify:
    - Restart Redpanda Console

- name: install | Enable systemd service unit
  ansible.builtin.systemd_service:
    no_block: false
    daemon_reload: true
    scope: system
    name: redpanda-console
    masked: false
    enabled: true
