---
- name: download | Create directory {{ redpanda_console_cache_download_path }}
  ansible.builtin.file:
    path: "{{ redpanda_console_cache_download_path }}"
    owner: root
    group: root
    mode: u=rw-x+X,g=r-x+X,o=r-x+X
    recurse: false
    state: directory
  register: redpanda_console_cache_download_directory

- name: download | Check if Red Panda Console package checksum exists
  ansible.builtin.stat:
    path: "{{ redpanda_console_cache_download_directory.path }}/checksums.v{{ redpanda_console_version }}.txt"
  register:
    redpanda_console_checksums_file_stat

- name: download | GET Red Panda Console release packages checksums
  ansible.builtin.get_url:
    url: "{{ redpanda_console_release_checksums_url }}"
    dest: "{{ redpanda_console_cache_download_directory.path }}/checksums.v{{ redpanda_console_version }}.txt"
    mode: u=rw-x,g=rw-x,o=r-x
    validate_certs: true
  when: >-
    (not redpanda_console_checksums_file_stat.stat.exists)

- name: download | Extract checksum line for Red Panda Console release package
  ansible.builtin.shell:
    chdir: "{{ redpanda_console_cache_download_directory.path }}"
    cmd: |
      set -e -u
      grep "redpanda-console-{{ redpanda_console_version }}-1.{{ redpanda_console_package_arch }}.{{ redpanda_console_package_format_file_suffix }}" \
      "./checksums.v{{ redpanda_console_version }}.txt"
    executable: "/bin/sh"
  changed_when: false # Just extracting the checksum line, so nothing has changed really.
  register: redpanda_console_package_checksum_line

- name: download | Extract SHA checksum from whole checksum line
  ansible.builtin.set_fact:
    redpanda_console_package_checksum: "{{ (redpanda_console_package_checksum_line.stdout | ansible.builtin.split('  '))[0] }}"
    redpanda_console_package_checksum_algorithm: sha256

- name: download | GET Red Panda Console package
  ansible.builtin.get_url:
    url: "{{ redpanda_console_package_download_url }}"
    dest: "{{ redpanda_console_cache_download_directory.path }}"
    force: false
    checksum: "{{ redpanda_console_package_checksum_algorithm }}:{{ redpanda_console_package_checksum }}"
    mode: u=rw-x,g=rw-x,o=r-x
    validate_certs: true
  register: redpanda_console_package_download_result
...
