---
# Calculated / composite variables
kafka_package_download_url: https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
kafka_checksum_sha512_download_url: "{{ kafka_package_download_url }}.sha512"
kafka_downloaded_checksum_file_path: "{{ kafka_cache_download_path }}/{{ kafka_checksum_sha512_download_url | ansible.builtin.basename }}"
kafka_downloaded_package_file_path: "{{ kafka_cache_download_path }}/{{ kafka_package_download_url | ansible.builtin.basename }}"

# Things that cannot be changed easily and are therefore hard-coded.
kafka_config_dir_path: "/etc/kafka"

# Default / fallback values
# See: https://developer.confluent.io/faq/apache-kafka/kafka-operations/
kafka_port_clients_default: '9092'
kafka_port_control_plane_default: '9093'
kafka_port_connect_default: '8083'
kafka_port_schema_registry_default: '8081'
kafka_port_rest_proxy_default: '8082'
kafka_port_ksqldb_default: '8088'
